spring.application.name=event-reader-app

eventreader.input-folder-path=C:/Users/97253/Desktop/input
eventreader.backup-folder-path=C:/Users/97253/Desktop/output
eventreader.scan-interval-ms=600000

spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springframework=INFO
logging.level.com.boriskoba=DEBUG
